### ISSUE TITLE
Main.php

### ISSUE THREAD

**Issue by CaitiffMCPE** [XFuryMCPE/TierLoot#1]
A player is already a location. No need for $p->getLocation(), learn the API

**Comment by legoboy0215** [comment]
It doesn't really matter.

**Comment by CaitiffMCPE** [comment]
So your small penis doesn't as well. <3

**Comment by 12341213414** [comment]
Whatever, kiddo. Just don't disturb me until I am done

**Comment by CaitiffMCPE** [comment]
My bad. He also doesn't know that loops exist. Go learn PHP as well <3

**Comment by CaitiffMCPE** [comment]
I can pull a request to fix the cute mess but it would be too easy. Lets leave him learn php and the api alone. Maybe he will learn something

**Comment by XFuryMCPE** [comment]
I made this around 6 months ago. I don't update it

**Comment by CaitiffMCPE** [comment]
My apologies.
